before_script:
  - whoami
  - sudo docker --version

stages:
  - build
  - deploy_staging
  - deploy

build:
  tags: 
    - rstudio
    - labs-az-01
  stage: build
  script: 
    - echo "Building the app in staging"
    - pwd; ls -la
    - ./build-test


deploy_staging:
  tags: 
    - rstudio
    - labs-az-01
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - pwd; ls -la
    - ./run-test-instance
  environment:
    name: staging
  only:
  - staging


deploy_production_01:
  tags: 
    - rstudio
    - labs-az-01
  stage: deploy
  script:
    - echo "Building the production app"
    - pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master

deploy_production_02:
  tags: 
    - rstudio
    - labs-az-02
  stage: deploy
  script:
    - echo "Building the production app"
    - pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master

deploy_production_03:
  tags: 
    - rstudio
    - labs-az-03
  stage: deploy
  script:
    - echo "Building the production app"
    - pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master

deploy_production_04:
  tags: 
    - rstudio
    - labs-az-04
  stage: deploy
  script:
    - echo "Building the production app"
    - pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master

deploy_production_08:
  tags: 
    - rstudio
    - labs-az-08
  stage: deploy
  script:
    - echo "Building the production app"
    - pwd; ls -la
    - ./build-production
    - echo "Deploy to production server"
    - cd /srv/persistent-data/docker-scripts; ./run-everything
  environment:
    name: production
  when: manual
  only:
  - master
